import os
import sys
# DON'T CHANGE THIS !!!
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# Added render_template, abort
from flask import Flask, send_from_directory, request, jsonify, render_template, abort 
from src.models.user import db, Usuario # Import db and Usuario model
from src.routes.auth import auth_bp
from src.routes.quiz import quiz_bp
from src.routes.chat import chat_bp
from src.routes.export import export_bp # Import the export blueprint

# Ensure templates directory exists relative to src
template_dir = os.path.join(os.path.dirname(__file__), 'src', 'templates')
static_dir = os.path.join(os.path.dirname(__file__), 'src', 'static')

app = Flask(__name__, 
            static_folder=static_dir,
            template_folder=template_dir)

app.config['SECRET_KEY'] = 'asdf#FGSgvasgf$5$WGT'

# Register blueprints
app.register_blueprint(auth_bp, url_prefix='/api/auth')
app.register_blueprint(quiz_bp, url_prefix='/api/quiz')
app.register_blueprint(chat_bp, url_prefix='/api/chat')
app.register_blueprint(export_bp, url_prefix='/api/export')

# --- Enable Database --- 
# Configuração do SQLite
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'orion_quiz.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

with app.app_context():
    print("Creating database tables if they don't exist...")
    db.create_all()
    print("Database tables checked/created.")
# --- End Database Setup ---

# --- Route for Shared Summary View ---
@app.route('/view/<string:access_code>')
def view_summary(access_code):
    try:
        user = Usuario.query.filter_by(codigo_acesso=access_code).first()
        if not user or not user.resumo_gerado:
            abort(404, description="Resumo não encontrado ou inválido.")

        # Basic language strings for the template
        lang_strings = {
            'pt': {
                'title': 'Resumo Compartilhado - Orion Quiz',
                'user_label': 'Usuário',
                'summary_title': 'Resumo Personalizado',
                'generated_by': 'Gerado por Orion Quiz'
            },
            'en': {
                'title': 'Shared Summary - Orion Quiz',
                'user_label': 'User',
                'summary_title': 'Personalized Summary',
                'generated_by': 'Generated by Orion Quiz'
            }
        }
        selected_lang = user.idioma if user.idioma in lang_strings else 'pt'
        strings = lang_strings[selected_lang]

        return render_template(
            'view_summary.html', 
            nick=user.nick,
            summary=user.resumo_gerado,
            lang=selected_lang,
            **strings # Pass language strings to template
        )
    except Exception as e:
        print(f"Erro ao exibir resumo compartilhado: {e}")
        abort(500, description="Erro interno ao carregar o resumo.")
# --- End Shared Summary Route ---

# Serve static files and index.html (SPA handling)
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve(path):
    # Avoid conflict with the /view/<access_code> route
    if path.startswith('view/'):
         # This case should be handled by the view_summary route
         # If it reaches here, something is wrong, maybe return 404
         abort(404)
         
    static_folder_path = app.static_folder
    if static_folder_path is None:
            return "Static folder not configured", 404

    if path != "" and os.path.exists(os.path.join(static_folder_path, path)):
        return send_from_directory(static_folder_path, path)
    else:
        index_path = os.path.join(static_folder_path, 'index.html')
        if os.path.exists(index_path):
            return send_from_directory(static_folder_path, 'index.html')
        else:
            return "index.html not found", 404


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)

